import { InsertFeedRegistry } from "@workspace/db";

// 50+ free & open sources per the blueprint spec.
// credibilityTier: 1=wire service, 2=established, 3=state media, 4=think tank/analysis
export const FEED_REGISTRY_SEED: InsertFeedRegistry[] = [
  // ─── Tier-1 Wire Services (5 min) ──────────────────────────────────────────
  {
    id: "reuters-world",
    name: "Reuters World News",
    url: "https://feeds.reuters.com/reuters/worldNews",
    type: "rss",
    credibilityTier: 1,
    isStateMedia: false,
    fetchIntervalSeconds: 300,
    parser: "rss",
  },
  {
    id: "ap-world",
    name: "AP News World",
    url: "https://apnews.com/hub/world-news/rss",
    type: "rss",
    credibilityTier: 1,
    isStateMedia: false,
    fetchIntervalSeconds: 300,
    parser: "rss",
  },
  {
    id: "afp-yahoo",
    name: "AFP via Yahoo World News",
    url: "https://news.yahoo.com/rss/world",
    type: "rss",
    credibilityTier: 1,
    isStateMedia: false,
    fetchIntervalSeconds: 300,
    parser: "rss",
  },
  {
    id: "bbc-world",
    name: "BBC World News",
    url: "https://feeds.bbci.co.uk/news/world/rss.xml",
    type: "rss",
    credibilityTier: 1,
    isStateMedia: false,
    fetchIntervalSeconds: 300,
    parser: "rss",
  },
  {
    id: "guardian-world",
    name: "The Guardian World",
    url: "https://www.theguardian.com/world/rss",
    type: "rss",
    credibilityTier: 1,
    isStateMedia: false,
    fetchIntervalSeconds: 300,
    parser: "rss",
  },
  {
    id: "nytimes-world",
    name: "New York Times World",
    url: "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
    type: "rss",
    credibilityTier: 1,
    isStateMedia: false,
    fetchIntervalSeconds: 300,
    parser: "rss",
  },

  // ─── Tier-2 Established Media (15 min) ────────────────────────────────────
  {
    id: "aljazeera-all",
    name: "Al Jazeera All",
    url: "https://www.aljazeera.com/xml/rss/all.xml",
    type: "rss",
    credibilityTier: 2,
    isStateMedia: false,
    fetchIntervalSeconds: 900,
    parser: "rss",
  },
  {
    id: "economist-world",
    name: "The Economist World",
    url: "https://www.economist.com/international/rss.xml",
    type: "rss",
    credibilityTier: 2,
    isStateMedia: false,
    fetchIntervalSeconds: 900,
    parser: "rss",
  },
  {
    id: "ft-world",
    name: "Financial Times World",
    url: "https://www.ft.com/world?format=rss",
    type: "rss",
    credibilityTier: 2,
    isStateMedia: false,
    fetchIntervalSeconds: 900,
    parser: "rss",
  },
  {
    id: "dw-world",
    name: "DW World",
    url: "https://rss.dw.com/rdf/rss-en-world",
    type: "rss",
    credibilityTier: 2,
    isStateMedia: false,
    fetchIntervalSeconds: 900,
    parser: "rss",
  },
  {
    id: "france24-world",
    name: "France 24 World",
    url: "https://www.france24.com/en/rss",
    type: "rss",
    credibilityTier: 2,
    isStateMedia: false,
    fetchIntervalSeconds: 900,
    parser: "rss",
  },
  {
    id: "japan-times-world",
    name: "Japan Times World",
    url: "https://www.japantimes.co.jp/feed/topstories",
    type: "rss",
    credibilityTier: 2,
    isStateMedia: false,
    fetchIntervalSeconds: 900,
    parser: "rss",
  },
  {
    id: "hindu-india",
    name: "The Hindu India",
    url: "https://www.thehindu.com/news/national/feeder/default.rss",
    type: "rss",
    credibilityTier: 2,
    isStateMedia: false,
    fetchIntervalSeconds: 900,
    parser: "rss",
  },
  {
    id: "mint-markets",
    name: "Mint Markets India",
    url: "https://www.livemint.com/rss/markets",
    type: "rss",
    credibilityTier: 2,
    isStateMedia: false,
    fetchIntervalSeconds: 900,
    parser: "rss",
  },
  {
    id: "et-markets",
    name: "Economic Times Markets",
    url: "https://economictimes.indiatimes.com/markets/rssfeeds/1977021501.cms",
    type: "rss",
    credibilityTier: 2,
    isStateMedia: false,
    fetchIntervalSeconds: 900,
    parser: "rss",
  },
  {
    id: "haaretz-world",
    name: "Haaretz World",
    url: "https://www.haaretz.com/srv/haaretz-eng-world",
    type: "rss",
    credibilityTier: 2,
    isStateMedia: false,
    fetchIntervalSeconds: 900,
    parser: "rss",
  },
  {
    id: "south-china-morning",
    name: "South China Morning Post World",
    url: "https://www.scmp.com/rss/91/feed",
    type: "rss",
    credibilityTier: 2,
    isStateMedia: false,
    fetchIntervalSeconds: 900,
    parser: "rss",
  },
  {
    id: "euronews-world",
    name: "Euronews World",
    url: "https://www.euronews.com/rss?level=theme&name=news",
    type: "rss",
    credibilityTier: 2,
    isStateMedia: false,
    fetchIntervalSeconds: 900,
    parser: "rss",
  },
  {
    id: "asia-times-world",
    name: "Asia Times",
    url: "https://asiatimes.com/feed/",
    type: "rss",
    credibilityTier: 2,
    isStateMedia: false,
    fetchIntervalSeconds: 900,
    parser: "rss",
  },

  // ─── Tier-3 State Media — Bias-flagged (15 min) ───────────────────────────
  {
    id: "tass-world",
    name: "TASS World",
    url: "https://tass.com/rss/v2.xml",
    type: "rss",
    credibilityTier: 3,
    isStateMedia: true,
    fetchIntervalSeconds: 900,
    parser: "rss",
  },
  {
    id: "xinhua-english",
    name: "Xinhua English",
    url: "https://www.xinhuanet.com/english/rss/worldrss.xml",
    type: "rss",
    credibilityTier: 3,
    isStateMedia: true,
    fetchIntervalSeconds: 900,
    parser: "rss",
  },
  {
    id: "farsnews-iran",
    name: "PressTV / Fars News",
    url: "https://en.farsnews.ir/rss.aspx",
    type: "rss",
    credibilityTier: 3,
    isStateMedia: true,
    fetchIntervalSeconds: 900,
    parser: "rss",
  },
  {
    id: "rt-world",
    name: "RT World (when accessible)",
    url: "https://www.rt.com/rss/news/",
    type: "rss",
    credibilityTier: 3,
    isStateMedia: true,
    fetchIntervalSeconds: 900,
    parser: "rss",
  },
  {
    id: "global-times",
    name: "Global Times China",
    url: "https://www.globaltimes.cn/rss/outbrain.xml",
    type: "rss",
    credibilityTier: 3,
    isStateMedia: true,
    fetchIntervalSeconds: 900,
    parser: "rss",
  },

  // ─── Official / Authoritative (15-30 min) ─────────────────────────────────
  {
    id: "un-news",
    name: "UN News",
    url: "https://news.un.org/feed/subscribe/en/news/all/rss.xml",
    type: "rss",
    credibilityTier: 1,
    isStateMedia: false,
    fetchIntervalSeconds: 900,
    parser: "rss",
  },
  {
    id: "ofac-sanctions",
    name: "OFAC Sanctions XML",
    url: "https://ofac.treasury.gov/system/files/126/cons_prim.xml",
    type: "api",
    credibilityTier: 1,
    isStateMedia: false,
    fetchIntervalSeconds: 1800,
    parser: "ofac",
  },
  {
    id: "rbi-press",
    name: "RBI Press Releases",
    url: "https://rbi.org.in/scripts/rss.aspx",
    type: "rss",
    credibilityTier: 1,
    isStateMedia: false,
    fetchIntervalSeconds: 1800,
    parser: "rss",
  },
  {
    id: "sebi-circulars",
    name: "SEBI Circulars RSS",
    url: "https://www.sebi.gov.in/sebiweb/home/HomeAction.do?doListing=yes&sid=1&ssid=3&smid=0",
    type: "rss",
    credibilityTier: 1,
    isStateMedia: false,
    fetchIntervalSeconds: 3600,
    parser: "rss",
  },

  // ─── Tier-4 Think Tanks & Policy (30 min) ─────────────────────────────────
  {
    id: "cfr-all",
    name: "CFR Publications",
    url: "https://www.cfr.org/rss/publication-feed/all",
    type: "rss",
    credibilityTier: 4,
    isStateMedia: false,
    fetchIntervalSeconds: 1800,
    parser: "rss",
  },
  {
    id: "brookings",
    name: "Brookings Institution",
    url: "https://www.brookings.edu/feed",
    type: "rss",
    credibilityTier: 4,
    isStateMedia: false,
    fetchIntervalSeconds: 1800,
    parser: "rss",
  },
  {
    id: "chatham-house",
    name: "Chatham House",
    url: "https://www.chathamhouse.org/rss.xml",
    type: "rss",
    credibilityTier: 4,
    isStateMedia: false,
    fetchIntervalSeconds: 1800,
    parser: "rss",
  },
  {
    id: "csis-analysis",
    name: "CSIS Analysis",
    url: "https://www.csis.org/rss.xml",
    type: "rss",
    credibilityTier: 4,
    isStateMedia: false,
    fetchIntervalSeconds: 1800,
    parser: "rss",
  },
  {
    id: "icg-reports",
    name: "International Crisis Group",
    url: "https://www.crisisgroup.org/rss.xml",
    type: "rss",
    credibilityTier: 4,
    isStateMedia: false,
    fetchIntervalSeconds: 1800,
    parser: "rss",
  },
  {
    id: "rand-research",
    name: "RAND Research",
    url: "https://www.rand.org/news.rss",
    type: "rss",
    credibilityTier: 4,
    isStateMedia: false,
    fetchIntervalSeconds: 1800,
    parser: "rss",
  },
  {
    id: "stimson-center",
    name: "Stimson Center",
    url: "https://www.stimson.org/feed/",
    type: "rss",
    credibilityTier: 4,
    isStateMedia: false,
    fetchIntervalSeconds: 1800,
    parser: "rss",
  },

  // ─── Structured Data Sources (30-60 min) ──────────────────────────────────
  {
    id: "gdelt-batch",
    name: "GDELT 2.0 Event Stream",
    url: "https://data.gdeltproject.org/gdeltv2/lastupdate.txt",
    type: "batch_csv",
    credibilityTier: 2,
    isStateMedia: false,
    fetchIntervalSeconds: 900,
    parser: "gdelt",
  },
  {
    id: "congress-api",
    name: "Congress.gov API",
    url: "https://api.congress.gov/v3/bill",
    type: "api",
    credibilityTier: 1,
    isStateMedia: false,
    fetchIntervalSeconds: 1800,
    parser: "congress",
  },
  {
    id: "acled-api",
    name: "ACLED Conflict Events",
    url: "https://api.acleddata.com/acled/read",
    type: "api",
    credibilityTier: 2,
    isStateMedia: false,
    fetchIntervalSeconds: 3600,
    parser: "acled",
  },
  {
    id: "worldbank-api",
    name: "World Bank Open Data",
    url: "https://api.worldbank.org/v2/country/all/indicator/NY.GDP.MKTP.CD",
    type: "api",
    credibilityTier: 1,
    isStateMedia: false,
    fetchIntervalSeconds: 604800, // weekly
    parser: "worldbank",
  },

  // ─── Additional Regional / Topic Sources ──────────────────────────────────
  {
    id: "dawn-pakistan",
    name: "Dawn Pakistan",
    url: "https://www.dawn.com/feeds/home",
    type: "rss",
    credibilityTier: 2,
    isStateMedia: false,
    fetchIntervalSeconds: 900,
    parser: "rss",
  },
  {
    id: "the-wire-india",
    name: "The Wire India",
    url: "https://thewire.in/rss",
    type: "rss",
    credibilityTier: 2,
    isStateMedia: false,
    fetchIntervalSeconds: 900,
    parser: "rss",
  },
  {
    id: "ndtv-india",
    name: "NDTV India",
    url: "https://feeds.feedburner.com/ndtvnews-india-news",
    type: "rss",
    credibilityTier: 2,
    isStateMedia: false,
    fetchIntervalSeconds: 900,
    parser: "rss",
  },
  {
    id: "middle-east-eye",
    name: "Middle East Eye",
    url: "https://www.middleeasteye.net/rss",
    type: "rss",
    credibilityTier: 2,
    isStateMedia: false,
    fetchIntervalSeconds: 900,
    parser: "rss",
  },
  {
    id: "africa-report",
    name: "The Africa Report",
    url: "https://www.theafricareport.com/feed/",
    type: "rss",
    credibilityTier: 2,
    isStateMedia: false,
    fetchIntervalSeconds: 1800,
    parser: "rss",
  },
  {
    id: "diplomat-asia",
    name: "The Diplomat Asia",
    url: "https://thediplomat.com/feed/",
    type: "rss",
    credibilityTier: 2,
    isStateMedia: false,
    fetchIntervalSeconds: 1800,
    parser: "rss",
  },
  {
    id: "war-on-rocks",
    name: "War on the Rocks",
    url: "https://warontherocks.com/feed/",
    type: "rss",
    credibilityTier: 4,
    isStateMedia: false,
    fetchIntervalSeconds: 1800,
    parser: "rss",
  },
  {
    id: "bellingcat",
    name: "Bellingcat",
    url: "https://www.bellingcat.com/feed/",
    type: "rss",
    credibilityTier: 2,
    isStateMedia: false,
    fetchIntervalSeconds: 1800,
    parser: "rss",
  },
  {
    id: "atlantic-council",
    name: "Atlantic Council",
    url: "https://www.atlanticcouncil.org/feed/",
    type: "rss",
    credibilityTier: 4,
    isStateMedia: false,
    fetchIntervalSeconds: 1800,
    parser: "rss",
  },
  {
    id: "relief-web",
    name: "ReliefWeb Humanitarian",
    url: "https://reliefweb.int/headlines/rss.xml",
    type: "rss",
    credibilityTier: 2,
    isStateMedia: false,
    fetchIntervalSeconds: 1800,
    parser: "rss",
  },
];
