#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# EC2 USER-DATA BOOTSTRAP for GNM "v2-nova-lite" instance
#
# Paste this entire script into the "User data" field when launching a fresh
# Ubuntu 24.04 EC2 instance. It runs as root once at first boot.
#
# What it does:
#   1. Installs Docker + Docker Compose + git
#   2. Clones the feat/market-layer-v2-nova-lite branch into /opt/gnm
#   3. Writes /opt/gnm/.env.production with Nova Lite + Bedrock + DB creds
#   4. Brings up the full Docker Compose stack (postgres, neo4j, chromadb,
#      api-server, frontend, caddy)
#   5. (Optional) Restores DB snapshots from S3 — only runs if SNAPSHOT_S3_URI
#      is set below
#
# What it does NOT do:
#   - Touch the existing prod instance at 65.0.93.40
#   - Push anything new to GitHub or Bedrock
#   - Set up a domain / TLS (Caddy serves HTTP on :80 until DOMAIN is set)
#
# After launch:
#   - SSH in: ssh -i <your-key.pem> ubuntu@<NEW_PUBLIC_IP>
#   - Tail logs: sudo tail -f /var/log/cloud-init-output.log
#   - Once Docker is up: cd /opt/gnm && sudo docker compose -f docker-compose.prod.yml --env-file .env.production ps
# ─────────────────────────────────────────────────────────────────────────────
set -euxo pipefail
exec > >(tee -a /var/log/gnm-bootstrap.log) 2>&1

GIT_URL="https://github.com/pratikbaswana-boop/Global-News-Monitor.git"
GIT_BRANCH="feat/market-layer-v2-nova-lite"
APP_DIR="/opt/gnm"

# ── CONFIG: edit these before pasting into User-data ────────────────────────
AWS_REGION_BEDROCK="us-east-1"
AWS_ACCESS_KEY_ID_BEDROCK="REPLACE_WITH_BEDROCK_ACCESS_KEY"
AWS_SECRET_ACCESS_KEY_BEDROCK="REPLACE_WITH_BEDROCK_SECRET_KEY"

# Optional: S3 URI containing DB snapshots (postgres.dump, neo4j.dump, chroma.tar.gz)
# Leave blank to start with empty DBs. See doc for snapshot creation commands.
SNAPSHOT_S3_URI=""   # e.g. "s3://gnm-snapshots/2026-05-27/"

# Strong random passwords for the databases on THIS new instance.
# (Different from existing prod so even snapshot restores keep their own creds.)
POSTGRES_PASSWORD="$(openssl rand -hex 24)"
NEO4J_PASSWORD="$(openssl rand -hex 24)"

# Optional news ingestion keys — leave blank if you don't want ingestion to run
NEWSAPI_KEY=""
GNEWS_KEY=""
GUARDIAN_KEY=""

# ── 1. Install Docker, git, awscli, jq ──────────────────────────────────────
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y ca-certificates curl gnupg lsb-release git jq unzip

install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
chmod a+r /etc/apt/keyrings/docker.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
  > /etc/apt/sources.list.d/docker.list
apt-get update -y
apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
usermod -aG docker ubuntu
systemctl enable --now docker

# AWS CLI v2
curl -fsSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
unzip -q /tmp/awscliv2.zip -d /tmp
/tmp/aws/install || /tmp/aws/install --update
rm -rf /tmp/awscliv2.zip /tmp/aws

# ── 2. Clone the new-feature branch ─────────────────────────────────────────
mkdir -p "$APP_DIR"
chown -R ubuntu:ubuntu "$APP_DIR"
sudo -u ubuntu git clone --depth 1 --branch "$GIT_BRANCH" "$GIT_URL" "$APP_DIR"

# ── 3. Write .env.production ────────────────────────────────────────────────
cat > "$APP_DIR/.env.production" <<EOF
# Generated by new-instance-bootstrap.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)
DOMAIN=:80

# LLM provider — Nova Lite via Bedrock (cheap, no throttling issues, no marketplace step)
LLM_PROVIDER=bedrock
LLM_MODEL_CHAT=amazon.nova-lite-v1:0
LLM_MODEL_EMBED=text-embedding-3-small

# Embeddings still need OpenAI (Bedrock embeddings not yet wired in lib/llm.ts)
# Leave dummy so semantic-dedup is a no-op rather than crashing
OPENAI_API_KEY=sk-dummy-disable-embedding
AI_INTEGRATIONS_OPENAI_BASE_URL=https://api.openai.com/v1

# Bedrock credentials (different from this EC2's instance-profile creds)
AWS_REGION=${AWS_REGION_BEDROCK}
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_BEDROCK}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_BEDROCK}

# Databases (fresh DBs on this new instance, isolated from prod)
POSTGRES_USER=gnm
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=gnm
NEO4J_USER=neo4j
NEO4J_PASSWORD=${NEO4J_PASSWORD}

# News ingestion
NEWSAPI_KEY=${NEWSAPI_KEY}
GNEWS_KEY=${GNEWS_KEY}
GUARDIAN_KEY=${GUARDIAN_KEY}
NEWS_FETCH_INTERVAL_HOURS=1

# NSE direct scraping (works from EC2 — Indian IP not required for Yahoo/NSE)
USE_NSE_DIRECT=true

LOG_LEVEL=info
EOF
chown ubuntu:ubuntu "$APP_DIR/.env.production"
chmod 600 "$APP_DIR/.env.production"

# ── 4. Build + start the Docker stack ───────────────────────────────────────
cd "$APP_DIR"
sudo -u ubuntu docker compose -f docker-compose.prod.yml --env-file .env.production build
sudo -u ubuntu docker compose -f docker-compose.prod.yml --env-file .env.production up -d postgres neo4j chromadb

# Wait for postgres + neo4j healthy
for i in {1..60}; do
  if sudo -u ubuntu docker compose -f docker-compose.prod.yml --env-file .env.production ps postgres | grep -q "healthy" && \
     sudo -u ubuntu docker compose -f docker-compose.prod.yml --env-file .env.production ps neo4j | grep -q "healthy"; then
    echo "DBs healthy after ${i}0s"
    break
  fi
  sleep 10
done

# ── 5. Run DB migrations ────────────────────────────────────────────────────
sudo -u ubuntu docker compose -f docker-compose.prod.yml --env-file .env.production run --rm migrate || true

# ── 6. Restore snapshots (if S3 URI provided) ──────────────────────────────
if [ -n "$SNAPSHOT_S3_URI" ]; then
  echo "Restoring DB snapshots from $SNAPSHOT_S3_URI"
  mkdir -p /tmp/gnm-restore
  aws s3 sync "$SNAPSHOT_S3_URI" /tmp/gnm-restore/

  # Postgres
  if [ -f /tmp/gnm-restore/postgres.dump ]; then
    sudo -u ubuntu docker compose -f docker-compose.prod.yml --env-file .env.production exec -T postgres \
      pg_restore -U gnm -d gnm --clean --if-exists < /tmp/gnm-restore/postgres.dump || true
  fi

  # Neo4j
  if [ -f /tmp/gnm-restore/neo4j.dump ]; then
    sudo -u ubuntu docker compose -f docker-compose.prod.yml --env-file .env.production stop neo4j
    sudo -u ubuntu docker cp /tmp/gnm-restore/neo4j.dump gnm_neo4j_prod:/var/lib/neo4j/data/neo4j.dump
    sudo -u ubuntu docker compose -f docker-compose.prod.yml --env-file .env.production exec -T neo4j \
      neo4j-admin database load --from-path=/var/lib/neo4j/data --overwrite-destination=true neo4j || true
    sudo -u ubuntu docker compose -f docker-compose.prod.yml --env-file .env.production start neo4j
  fi

  # Chroma — its data is a directory; just copy in
  if [ -f /tmp/gnm-restore/chroma.tar.gz ]; then
    sudo -u ubuntu docker compose -f docker-compose.prod.yml --env-file .env.production stop chromadb
    sudo -u ubuntu docker cp /tmp/gnm-restore/chroma.tar.gz gnm_chromadb_prod:/tmp/chroma.tar.gz
    sudo -u ubuntu docker compose -f docker-compose.prod.yml --env-file .env.production exec -T chromadb \
      tar xzf /tmp/chroma.tar.gz -C /chroma/chroma || true
    sudo -u ubuntu docker compose -f docker-compose.prod.yml --env-file .env.production start chromadb
  fi

  rm -rf /tmp/gnm-restore
fi

# ── 7. Bring up the rest of the stack ──────────────────────────────────────
sudo -u ubuntu docker compose -f docker-compose.prod.yml --env-file .env.production up -d

# ── 8. Smoke check ──────────────────────────────────────────────────────────
sleep 20
sudo -u ubuntu docker compose -f docker-compose.prod.yml --env-file .env.production ps
curl -fsS http://localhost/ -o /dev/null -w "HTTP %{http_code} on /\n" || true
curl -fsS http://localhost:3000/ -o /dev/null -w "HTTP %{http_code} on api :3000\n" || true

echo "──────────────────────────────────────────────────────────"
echo "Bootstrap complete."
echo "  UI:    http://$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)/"
echo "  API:   http://$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4):3000/"
echo "  Logs:  /var/log/gnm-bootstrap.log"
echo "──────────────────────────────────────────────────────────"
